[masters]
k8s-master-01 ansible_host=10.0.50.11 ansible_user=root
k8s-master-02 ansible_host=10.0.50.12 ansible_user=root
k8s-master-03 ansible_host=10.0.50.13 ansible_user=root

[workers]
k8s-worker-01 ansible_host=10.0.50.21 ansible_user=root
k8s-worker-02 ansible_host=10.0.50.22 ansible_user=root
k8s-worker-03 ansible_host=10.0.50.23 ansible_user=root
k8s-worker-04 ansible_host=10.0.50.24 ansible_user=root
k8s-worker-05 ansible_host=10.0.50.25 ansible_user=root

[k8s:children]
masters
workers
