# 02-provisioning/requirements.yml
roles:
  - name: geerlingguy.containerd
    version: 1.4.1
  - name: geerlingguy.kubernetes
    version: 4.0.2

collections:
  - name: kubernetes.core
    version: 6.4.0
  - name: community.hashi_vault
    version: 7.1.0
