---
- name: Execute join command on nodes
  ansible.builtin.command: "{{ hostvars['k8s-master-01'].join_command }}"
  args:
    creates: /etc/kubernetes/kubelet.conf
  register: join_out
  until: join_out is succeeded
  retries: 5
  delay: 10

- name: Label nodes as workers
  ansible.builtin.command: "kubectl label node {{ item }} node-role.kubernetes.io/worker=worker --overwrite"
  delegate_to: k8s-master-01
  loop: "{{ groups['workers'] | default([]) }}"
  run_once: true
  failed_when: false

- name: Label secondary masters
  ansible.builtin.command: "kubectl label node {{ item }} node-role.kubernetes.io/control-plane= --overwrite"
  delegate_to: k8s-master-01
  loop:
    - k8s-master-02
    - k8s-master-03
  run_once: true
  failed_when: false

- name: Restart kubelet
  ansible.builtin.systemd:
    name: kubelet
    state: restarted
